Skh/godot intrinsics
funexpected/ECMAScript pull request #1
Opened 2021-06-22 13:36 UTC by sergey-khrykov

2021-06-23 18:15 UTC, sergey-khrykov commented on quickjs/quickjs/quickjs.h
> +void JS_AddIntrinsicGodotPrimitives(JSContext *ctx);
добавил #ifdef CONFIG_GODOT_INTRINSICS

2021-06-23 18:15 UTC, sergey-khrykov commented on quickjs/quickjs_binder.cpp
> + 			return js_to_vector2(ctx, p_val);
добавил #ifdef CONFIG_GODOT_INTRINSICS

2021-06-23 18:17 UTC, sergey-khrykov commented on quickjs/quickjs/quickjs.c
> +    case JS_TAG_VECTOR2:
добавил #ifdef CONFIG_GODOT_INTRINSICS

2021-06-23 18:17 UTC, sergey-khrykov commented on quickjs/quickjs/quickjs.c
> +    case JS_TAG_VECTOR2:
добавил #ifdef CONFIG_GODOT_INTRINSICS

2021-06-24 05:53 UTC, sergey-bychenko commented on godot_intrinsics/free_list_alloc.h
> +
Структуру я прочитать могу, но мне не ясна её задача. Мы собираем список всей аллокации чтоб потом это удалять или есть ещё какие-то задачи?

2021-06-24 06:01 UTC, sergey-bychenko commented on quickjs/quickjs/quickjs.h
> +#ifdef CONFIG_GODOT_INTRINSICS
Вот этот файл не понимаю, хотелось бы устно выслушать что тут происходит

2021-06-24 06:47 UTC, jkb0o reviewed
огнище. 
хочеться дозакрывать всё `#ifdef CONFIG_GODOT_INTRINSICS`?
я бы ещё пару минимальных методов в rect добавил типа `expand` `move`, `resize` и `contains`

2021-06-24 06:47 UTC, jkb0o commented on godot_intrinsics/free_list_alloc.h
> +
мы хотим уменьшить количество аллокаций. паттерн называется Memory Pool. у нас много маленьких стркуктур (типа Vector2 и Rect2). Каждый раз когда в js создаётся объект этого типа, аллоцируется эта структура. мы не хотим аллоцировать. вместо этого мы запоминаем все аллоцированные объекты, и когда нужен новый - выдаём из этого pool'а. когда структура больше не нужна, вы вместо освобождения памяти возвращаем её в pool.

таким образом у нас висит в памяти какое-то количество объектов, а новых аллокаций не происходит.

2021-06-24 06:47 UTC, jkb0o commented on godot_intrinsics/godot_intrinsic_types.c
> +        goto new_vector;
а как со стороны js добиться вызова этой функции?

2021-06-24 06:47 UTC, jkb0o commented on quickjs/quickjs/quickjs.c
> +
нужно завернуть в `#ifdef CONFIG_GODOT_INTRINSICS`?

2021-06-24 06:47 UTC, jkb0o commented on quickjs/quickjs/quickjs.c
> +    JS_AddIntrinsicGodotPrimitives(ctx);
нужно завернуть в `#ifdef CONFIG_GODOT_INTRINSICS`?

2021-06-24 06:47 UTC, jkb0o commented on quickjs/quickjs/quickjs.c
> +        case JS_CLASS_RECT2:             /* u.rect2 */
нужно завернуть в `#ifdef CONFIG_GODOT_INTRINSICS`?

2021-06-24 06:47 UTC, jkb0o commented on quickjs/quickjs/quickjs.c
> +    case JS_TAG_VECTOR2:
не вижу

2021-06-24 06:47 UTC, jkb0o commented on quickjs/quickjs/quickjs.c
> +    case JS_TAG_VECTOR2:
не понимаю где добавил

2021-06-24 06:47 UTC, jkb0o commented on quickjs/quickjs/quickjs.h
> +#ifdef CONFIG_GODOT_INTRINSICS
я боюсь мы тоже его не очень понимаем. это заголовочный файл движка quickjs, который парсит javascript, компилирует в байт-код и исполняет его. 

в js есть понятие `JSValue` - штука очень похожа на `Variant`. состоит из заголовка (что это за значение) и куска памяти для значения. по умолчанию javascript умеет ограниченное число типов value - number, string, null, object. этого нам недостаточно. мы хотим, чтобы примитивные типа Godot были очень маленькими Value-типами, а не наследовались от JSObject. здесь мы добавляем собственные тэги в JSValue, расширяем таким образом Godot-примитивами.

2021-06-24 11:12 UTC, sergey-khrykov commented on godot_intrinsics/free_list_alloc.h
> +
Сокращаем число вызовов malloc, беря на себя часть менеджмента памяти. Должно помочь при активной работе с Rect2 и Vector2

2021-06-24 11:15 UTC, sergey-khrykov commented on quickjs/quickjs/quickjs.c
> +
добавил

2021-06-24 11:15 UTC, sergey-khrykov commented on quickjs/quickjs/quickjs.c
> +    JS_AddIntrinsicGodotPrimitives(ctx);
уже поправил

2021-06-24 11:27 UTC, sergey-khrykov commented on quickjs/quickjs/quickjs.c
> +    case JS_TAG_VECTOR2:
запушил

2021-06-24 11:28 UTC, sergey-khrykov commented on quickjs/quickjs/quickjs.h
> +#ifdef CONFIG_GODOT_INTRINSICS
Я могу сделать рассказ — прогулку по этому коду, когда продвинемся дальше. Пока что сам не все тут понимаю

2021-06-25 13:29 UTC, jkb0o requested changes
всё кайф кроме `intersect`'а

2021-06-25 13:29 UTC, jkb0o commented on godot_intrinsics/rect2.c
> +        js_rect2_contains_internal(rect2, &rect1->position);
мне кажется тут чуть сложнее. что насчёт ректов `крестом`?
```
  ,-,
,_|_|_,
|_|_|_|
  |_|
```

2021-06-28 20:10 UTC, jkb0o approved these changes

2021-06-28 20:11 UTC, merged